import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,900);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;document.body.appendChild(renderer.domElement);

const WORLD=new THREE.Group();const ROAD=new THREE.Group();const TRAFFIC=new THREE.Group();scene.add(WORLD,ROAD,TRAFFIC);
const state={car:'supra',env:'neon',mode:'infinite',speed:0,nitro:100,distance:0,score:0,cam:0,crashed:false,running:false,last:performance.now(),lane:2,steer:0};
const keys={};const lanes=[-5.66,-2.83,0,2.83,5.66];
const defs={supra:{name:'SUPRA-X',color:0xff741b,max:112,acc:30,handling:9,owned:true},gtr:{name:'GTR-X',color:0xe8edf3,max:120,acc:29,handling:10,owned:true},gt:{name:'GT-V12',color:0x236cff,max:128,acc:27,handling:8,owned:false,price:85000},rally:{name:'RALLY-X',color:0xff315c,max:106,acc:33,handling:11,owned:false,price:120000}};
const I18N={en:{race:'Race',garage:'Garage',shop:'Shop',custom:'Customize',leader:'Leaderboard',settings:'Settings',play:'PLAY',modes:'Race Modes'},fa:{race:'مسابقه',garage:'گاراژ',shop:'فروشگاه',custom:'شخصی‌سازی',leader:'لیدربورد',settings:'تنظیمات',play:'بازی',modes:'حالت‌های مسابقه'},ar:{race:'سباق',garage:'الكراج',shop:'المتجر',custom:'تخصيص',leader:'المتصدرين',settings:'الإعدادات',play:'ابدأ',modes:'أنماط السباق'},es:{race:'Carrera',garage:'Garaje',shop:'Tienda',custom:'Personalizar',leader:'Clasificación',settings:'Ajustes',play:'JUGAR',modes:'Modos de carrera'},tr:{race:'Yarış',garage:'Garaj',shop:'Mağaza',custom:'Özelleştir',leader:'Liderlik',settings:'Ayarlar',play:'OYNA',modes:'Yarış Modları'}};
let lang=localStorage.ldLang||'en';
function M(color,metal=.45,rough=.25,em=0){return new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough,emissive:em,emissiveIntensity:em?2.2:0})}
function addBox(g,w,h,d,color,x,y,z,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat||M(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
function bodyShape(color){const s=new THREE.Shape();s.moveTo(-1.02,.34);s.lineTo(-.98,.68);s.lineTo(-.78,.9);s.lineTo(-.58,.94);s.lineTo(-.36,1.25);s.lineTo(.34,1.27);s.lineTo(.62,.96);s.lineTo(.9,.88);s.lineTo(1.02,.55);s.lineTo(1.02,.34);s.closePath();const geo=new THREE.ExtrudeGeometry(s,{depth:4.35,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.08,bevelThickness:.06});geo.center();geo.rotateY(Math.PI);const m=new THREE.Mesh(geo,M(color,.7,.2));m.castShadow=true;m.receiveShadow=true;return m}
function sportsCar(def,traffic=false){const g=new THREE.Group();const body=bodyShape(def.color);body.position.y=.08;g.add(body);
const glassMat=M(0x0b1624,.65,.12);const cabin=addBox(g,1.48,.48,1.75,0,0,1.02,-.15,glassMat);cabin.scale.y=.92;
const windshield=addBox(g,1.28,.055,.98,0,0,1.02,-.7,M(0x58cfff,.5,.08,.06));windshield.rotation.x=-.12;
addBox(g,1.92,.11,.18,0,0,1.38,1.82,M(def.color,.7,.18));addBox(g,1.95,.12,.16,0,0,.62,-2.18,M(0x111318,.7,.2));
const head=M(0xf4fbff,.3,.12,.3),tail=M(0xff164d,.2,.1,.4);addBox(g,.52,.09,.14,0,-.62,.88,-2.2,head);addBox(g,.52,.09,.14,0,.62,.88,-2.2,head);addBox(g,.55,.08,.12,0,-.68,.83,2.19,tail);addBox(g,.55,.08,.12,0,.68,.83,2.19,tail);
for(const x of[-.98,.98])for(const z of[-1.48,1.48]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.37,.37,.28,24),M(0x08090c,.1,.8));w.rotation.z=Math.PI/2;w.position.set(x,.38,z);w.castShadow=true;g.add(w);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.3,20),M(def.color,.8,.18));rim.rotation.z=Math.PI/2;rim.position.set(x,.38,z);g.add(rim)}
if(!traffic){const glow=M(0x15d8ff,.2,.15,.25);addBox(g,1.55,.045,.1,0,0,.48,2.25,glow)}return g}

let player=sportsCar(defs[state.car]);player.position.set(0,0,7);scene.add(player);

function setEnvironment(){const e=state.env;let sky=0x070a18,ground=0x101522,road=0x262a32;if(e==='day'){sky=0x8cb6d4;ground=0x476b49;road=0x34383e}if(e==='sunset'){sky=0x3b2030;ground=0x392824;road=0x2c2b32}if(e==='desert'){sky=0xd79a65;ground=0x9d6942;road=0x353238}scene.background=new THREE.Color(sky);scene.fog=new THREE.Fog(sky,75,430);scene.children.filter(x=>x.isLight).forEach(x=>scene.remove(x));const hemi=new THREE.HemisphereLight(e==='day'?0xddeeff:0x9da9ff,0x15151c,2.15);scene.add(hemi);const sun=new THREE.DirectionalLight(e==='sunset'?0xffb06b:0xffffff,2.8);sun.position.set(-35,75,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-80;sun.shadow.camera.right=80;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;scene.add(sun);
while(WORLD.children.length)WORLD.remove(WORLD.children[0]);while(ROAD.children.length)ROAD.remove(ROAD.children[0]);
const gmat=M(ground,.05,.95),rmat=M(road,.1,.78),shoulder=M(e==='neon'?0x171d29:e==='desert'?0xb37a4e:0x59635c,.1,.9),line=M(0xe9e4d7,.1,.65),rail=M(e==='neon'?0x2d5cff:0x6b737a,.65,.25,e==='neon'?0x182bff:0);
const plane=new THREE.Mesh(new THREE.PlaneGeometry(700,1300),gmat);plane.rotation.x=-Math.PI/2;plane.position.z=-280;WORLD.add(plane);
for(let i=0;i<42;i++){const z=35-i*32;const seg=new THREE.Group();const rm=new THREE.Mesh(new THREE.PlaneGeometry(18,32),rmat);rm.rotation.x=-Math.PI/2;rm.position.y=.015;seg.add(rm);for(const x of[-9.7,9.7]){addBox(seg,.5,.18,32,0x30343c,x,.08,0,rail);addBox(seg,1.7,.04,32,shoulder,x*1.02,.035,0)}for(const x of[-4.25,-1.42,1.42,4.25]){const lm=new THREE.Mesh(new THREE.PlaneGeometry(.12,4.8),line);lm.rotation.x=-Math.PI/2;lm.position.set(x,.045,-3);seg.add(lm)}
if(i%2===0){for(const x of[-11.5,11.5]){const pole=addBox(seg,.12,5.5,.12,e==='neon'?0x202638:0x52575c,x,2.75,7);const lamp=new THREE.Mesh(new THREE.SphereGeometry(.16,12,8),M(e==='neon'?0x33cfff:0xfff1b0,.1,.15,e==='neon'?0x22cfff:0xffd36b));lamp.position.set(x,5.45,7);seg.add(lamp)}}seg.position.z=z;ROAD.add(seg)}
if(e==='neon'){for(let i=0;i<45;i++){const side=i%2?-1:1,x=side*(13+Math.random()*24),z=-i*24-Math.random()*18,h=5+Math.random()*20,w=3+Math.random()*5;const b=addBox(WORLD,w,h,w,0x11172a,x,h/2,z);if(i%3===0){const n=addBox(WORLD,w*.82,.13,.13,i%2?0xff35bd:0x20d9ff,x,h*.68,z-w/2,M(i%2?0xff35bd:0x20d9ff,.1,.12,i%2?0xff35bd:0x20d9ff))}}}else{for(let i=0;i<45;i++){const side=i%2?-1:1,x=side*(14+Math.random()*25),z=-i*29-Math.random()*18,h=3+Math.random()*10,w=2+Math.random()*5;addBox(WORLD,w,h,w,e==='desert'?0x8f6044:0x3b4b43,x,h/2,z)}}}
setEnvironment();

const traffic=[];const trafficColors=[0xffffff,0x161a21,0xd93d55,0xffc72c,0x4776ff,0x24b36b,0x9b6cff];
function spawnTraffic(i){const d={color:trafficColors[i%trafficColors.length],max:80};const c=sportsCar(d,true);c.position.set(lanes[(i*3)%5],0,-40-i*32-Math.random()*30);c.userData.speed=48+Math.random()*48;c.userData.lane=(i*3)%5;c.userData.change=3+Math.random()*8;TRAFFIC.add(c);traffic.push(c)}for(let i=0;i<22;i++)spawnTraffic(i);

function reset(){state.speed=0;state.nitro=100;state.distance=0;state.score=0;state.crashed=false;player.position.set(0,0,7);player.rotation.set(0,0,0);document.getElementById('crashOverlay')?.remove();traffic.forEach((t,i)=>{t.position.set(lanes[(i*3)%5],0,-40-i*34-Math.random()*35);t.userData.speed=42+Math.random()*52;t.userData.lane=Math.round((t.position.x+5.66)/2.83)})}
function crash(){if(state.crashed)return;state.crashed=true;state.speed*=.25;const d=document.createElement('div');d.id='crashOverlay';d.style.cssText='position:fixed;inset:0;z-index:30;display:grid;place-items:center;background:#05071199;backdrop-filter:blur(5px);font-family:system-ui;color:white;text-align:center';d.innerHTML='<div><div style="font-size:64px;font-weight:1000;font-style:italic;color:#ff4b1d">CRASH</div><div style="opacity:.8">Press R to restart</div></div>';document.body.appendChild(d)}
function start(){document.getElementById('menu').style.display='none';document.getElementById('hud').style.display='flex';document.getElementById('back').style.display='block';state.running=true;reset()}
function stop(){state.running=false;document.getElementById('menu').style.display='flex';document.getElementById('hud').style.display='none';document.getElementById('back').style.display='none'}
function modal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function openPanel(type){const d=defs[state.car];if(type==='modes')modal(I18N[lang].modes,`<div class="grid">${[['infinite','∞','Infinite'],['time','◷','Against Time'],['two','↕','Two Way'],['free','▥','Free Ride']].map(x=>`<button class="choice" data-mode="${x[0]}"><b style="font-size:28px">${x[1]}</b><h3>${x[2]}</h3></button>`).join('')}</div><h3>Environment</h3><div class="grid">${[['neon','🌃','City Night'],['day','☀️','Highway Day'],['sunset','🌇','Sunset'],['desert','🏜️','Desert']].map(x=>`<button class="choice" data-env="${x[0]}">${x[1]} ${x[2]}</button>`).join('')}</div><button class="play" id="startRace">PLAY ▶</button>`);else if(type==='garage')modal(I18N[lang].garage,`<div class="grid">${Object.entries(defs).map(([k,v])=>`<button class="choice" data-car="${k}"><div class="swatch" style="height:80px;border-radius:10px;background:linear-gradient(135deg,#111,#${v.color.toString(16).padStart(6,'0')})"></div><b>${v.name}</b><br><small>${Math.round(v.max*3.35)} KM/H · Handling ${v.handling}/10</small></button>`).join('')}</div>`);else if(type==='shop')modal(I18N[lang].shop,`<div class="grid"><div class="choice"><h3>💵 Cash</h3><p>+25,000</p><button class="play" data-buy="cash">CLAIM</button></div><div class="choice"><h3>💎 Gems</h3><p>+50</p><button class="play" data-buy="gems">CLAIM</button></div></div>`);else if(type==='custom')modal(I18N[lang].custom,`<h2>${d.name}</h2><div class="grid">${['Paint','Rims','Spoiler','Vinyl','Tint','Engine','Turbo','Brakes'].map((x,i)=>`<button class="choice" data-custom="${i}"><b>${x}</b><p style="opacity:.65">UPGRADE</p></button>`).join('')}</div>`);else if(type==='leader'){let scores=JSON.parse(localStorage.ldScores||'[]');scores.sort((a,b)=>b.score-a.score);if(!scores.length)scores=[{name:'LEGEND',score:12560},{name:'NEONFOX',score:9870},{name:'RACER_77',score:9120}];modal(I18N[lang].leader,'<p>Global-ready UI. Online backend can be attached later.</p>'+scores.slice(0,10).map((x,i)=>`<div class="choice" style="margin:7px 0"><b>#${i+1} ${x.name}</b><span style="float:right">${Math.floor(x.score)}</span></div>`).join(''));}else modal(I18N[lang].settings,'<div class="grid"><button class="choice">Graphics: HIGH</button><button class="choice">60 FPS TARGET</button><button class="choice" id="resetData">RESET DATA</button></div><p>WASD / Arrows · Shift Nitro · C Camera · R Restart</p>')}

document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPanel(b.dataset.open));document.getElementById('close').onclick=closeModal;document.getElementById('back').onclick=stop;
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.ldLang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'||lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('on',x.dataset.lang===lang));document.querySelectorAll('[data-t]').forEach(e=>e.textContent=I18N[lang][e.dataset.t])});
document.getElementById('modalBody').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){state.mode=b.dataset.mode;openPanel('modes')}if(b.dataset.env){state.env=b.dataset.env;setEnvironment();openPanel('modes')}if(b.dataset.car){const v=defs[b.dataset.car];if(v.owned||state.car==='supra'){state.car=b.dataset.car;scene.remove(player);player=sportsCar(v);player.position.set(0,0,7);scene.add(player);openPanel('garage')}}if(b.id==='startRace')start();if(b.dataset.buy==='cash'){localStorage.ldCash=(+(localStorage.ldCash||25000))+25000}if(b.dataset.buy==='gems'){localStorage.ldGems=(+(localStorage.ldGems||120))+50}if(b.id==='resetData'){localStorage.clear();location.reload()}});

addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyC')state.cam=(state.cam+1)%4;if(e.code==='KeyR')reset()});addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('.touch').forEach(b=>{const k=b.dataset.key;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

function update(dt,now){if(!state.running||state.crashed)return;const d=defs[state.car];const gas=keys.KeyW||keys.ArrowUp,brake=keys.KeyS||keys.ArrowDown;let steer=((keys.KeyD||keys.ArrowRight)?1:0)-((keys.KeyA||keys.ArrowLeft)?1:0);if(gas)state.speed+=d.acc*dt;else state.speed-=7*dt;if(brake)state.speed-=44*dt;const boost=(keys.ShiftLeft||keys.ShiftRight)&&state.nitro>0;if(boost){state.speed+=58*dt;state.nitro-=42*dt}else state.nitro=Math.min(100,state.nitro+11*dt);state.speed=Math.max(0,Math.min(d.max,state.speed));const targetSteer=steer*(1.9+state.speed*.032);state.steer=THREE.MathUtils.damp(state.steer,targetSteer,8,dt);player.position.x+=state.steer*dt;player.position.x=THREE.MathUtils.clamp(player.position.x,-7.05,7.05);player.rotation.z=THREE.MathUtils.damp(player.rotation.z,-steer*.09,7,dt);player.rotation.y=THREE.MathUtils.damp(player.rotation.y,steer*.025,7,dt);state.distance+=state.speed*dt*.34;state.score+=state.speed*dt*(boost?1.8:1);
for(const t of traffic){t.position.z+=(state.speed-t.userData.speed)*dt;if(t.position.z>player.position.z+35){t.position.z=player.position.z-520-Math.random()*250;t.userData.lane=Math.floor(Math.random()*5);t.position.x=lanes[t.userData.lane];t.userData.speed=42+Math.random()*54}if(Math.abs(t.position.x-player.position.x)<1.65&&Math.abs(t.position.z-player.position.z)<2.55)crash()}
ROAD.children.forEach(seg=>{if(seg.position.z>player.position.z+40)seg.position.z-=42*32});WORLD.children.forEach(o=>{if(o.position.z>player.position.z+45)o.position.z-=45*30});}
function render(now){const target=[new THREE.Vector3(player.position.x,4.3,player.position.z+10),new THREE.Vector3(player.position.x,2.1,player.position.z+5.5),new THREE.Vector3(player.position.x,8.5,player.position.z+15),new THREE.Vector3(player.position.x,1.45,player.position.z-2.8)][state.cam];camera.position.lerp(target,.085);camera.lookAt(player.position.x,.75,player.position.z-18);document.getElementById('speed').textContent=Math.round(state.speed*3.35);document.getElementById('distance').textContent=Math.floor(state.distance)+' m';document.getElementById('score').textContent=Math.floor(state.score);document.getElementById('nitro').textContent=Math.floor(state.nitro)+'%';renderer.render(scene,camera)}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt,now);render(now);requestAnimationFrame(loop)}
requestAnimationFrame(loop);
