import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101722);scene.fog=new THREE.Fog(0x101722,70,320);const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,700);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xaecbff,0x26301f,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-40,70,30);scene.add(sun);
const grass=new THREE.Mesh(new THREE.PlaneGeometry(700,700),new THREE.MeshStandardMaterial({color:0x263425}));grass.rotation.x=-Math.PI/2;scene.add(grass);
const road=new THREE.Mesh(new THREE.PlaneGeometry(20,700),new THREE.MeshStandardMaterial({color:0x292c31,roughness:.9}));road.rotation.x=-Math.PI/2;road.position.y=.02;scene.add(road);
for(const x of [-9,-3,3,9]){const edge=new THREE.Mesh(new THREE.PlaneGeometry(.11,700),new THREE.MeshBasicMaterial({color:0xffffff}));edge.rotation.x=-Math.PI/2;edge.position.set(x,.035,0);scene.add(edge)}
for(let z=-340;z<340;z+=12)for(const x of [-6,0,6]){const d=new THREE.Mesh(new THREE.PlaneGeometry(.16,5),new THREE.MeshBasicMaterial({color:0xf1f1d6}));d.rotation.x=-Math.PI/2;d.position.set(x,.04,z);scene.add(d)}
function carModel(color,scale=1){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.1,.58,4.25),new THREE.MeshStandardMaterial({color,metalness:.55,roughness:.24}));body.position.y=.65;g.add(body);const hood=new THREE.Mesh(new THREE.BoxGeometry(1.85,.25,1.15),new THREE.MeshStandardMaterial({color,metalness:.45,roughness:.2}));hood.position.set(0,.98,-1.25);g.add(hood);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.55,.58,1.75),new THREE.MeshStandardMaterial({color:0x172338,metalness:.2,roughness:.1}));cabin.position.set(0,1.08,.25);g.add(cabin);for(const x of [-1.02,1.02])for(const z of [-1.42,1.42]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.36,.36,.26,24),new THREE.MeshStandardMaterial({color:0x08090b,roughness:.85}));w.rotation.z=Math.PI/2;w.position.set(x,.4,z);g.add(w)}g.scale.setScalar(scale);return g}
const player=carModel(0x20a4ff,1);player.position.set(0,0,20);scene.add(player);
const traffic=[];const colors=[0xe84d4d,0xffffff,0xf2bd3f,0x6c78d8,0x43b36b,0x22252b];for(let i=0;i<12;i++){const lane=[-6,-3,0,3,6][i%5],t=carModel(colors[i%colors.length],.92+Math.random()*.08);t.position.set(lane,0,-30-i*32-Math.random()*40);t.userData.speed=.55+Math.random()*.35;scene.add(t);traffic.push(t)}
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR'){player.position.set(0,0,20);speed=0;distance=0;gameOver=false}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let speed=0,nitro=100,distance=0,score=0,gameOver=false,last=performance.now();function hit(a,b){return Math.abs(a.position.x-b.position.x)<1.65&&Math.abs(a.position.z-b.position.z)<3.1}function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(!gameOver){const gas=keys.KeyW||keys.ArrowUp,brake=keys.KeyS||keys.ArrowDown;if(gas)speed+=30*dt;else speed-=8*dt;if(brake)speed-=34*dt;if((keys.ShiftLeft||keys.ShiftRight)&&nitro>0){speed+=48*dt;nitro-=40*dt}else nitro=Math.min(100,nitro+8*dt);speed=Math.max(0,Math.min(85,speed));let steer=((keys.KeyD||keys.ArrowRight)?-1:0)+((keys.KeyA||keys.ArrowLeft)?1:0);player.position.x+=steer*(7.5+speed*.08)*dt;player.position.x=Math.max(-7.6,Math.min(7.6,player.position.x));player.rotation.z=-steer*.055;player.rotation.y=steer*.045;distance+=speed*dt;score+=speed*dt*1.5;for(const t of traffic){t.position.z+=(speed*t.userData.speed)*dt;if(t.position.z>player.position.z+35){t.position.z=player.position.z-300-Math.random()*180;t.position.x=[-6,-3,0,3,6][Math.floor(Math.random()*5)];t.userData.speed=.55+Math.random()*.35}if(hit(player,t))gameOver=true}}
const target=new THREE.Vector3(player.position.x*.7,5.3,player.position.z+12);camera.position.lerp(target,.09);camera.lookAt(player.position.x,1.1,player.position.z-18);document.getElementById('speed').textContent=Math.round(speed*3.25);document.getElementById('distance').textContent=Math.floor(distance);document.getElementById('score').textContent=Math.floor(score);document.getElementById('nitro').textContent=Math.floor(nitro);document.getElementById('state').textContent=gameOver?'CRASH — PRESS R':'DRIVE';renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);