import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x080a13,55,330);const camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,700);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xa8c8ff,0x111522,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-30,80,20);sun.castShadow=true;scene.add(sun);
const state={speed:0,nitro:100,distance:0,score:0,cam:0,twoWay:false,crashed:false,env:'neon',car:'gtr',last:performance.now()};const keys={};
const I18N={en:{title:'LEGEND DRIVE',desc:'Neon highway arcade racing',speed:'SPEED',dist:'DIST',score:'SCORE',nitro:'NITRO',restart:'Restart R',camera:'Camera C'},fa:{title:'لجند درایو',desc:'مسابقه آرکید در بزرگراه نئونی',speed:'سرعت',dist:'مسافت',score:'امتیاز',nitro:'نیترو',restart:'شروع دوباره R',camera:'دوربین C'},ar:{title:'ليجند درايف',desc:'سباق أركيد على طريق سريع نيون',speed:'السرعة',dist:'المسافة',score:'النقاط',nitro:'نيترو',restart:'إعادة R',camera:'الكاميرا C'},es:{title:'LEGEND DRIVE',desc:'Carreras arcade en autopista',speed:'VELOCIDAD',dist:'DIST',score:'PUNTOS',nitro:'NITRO',restart:'Reiniciar R',camera:'Cámara C'},tr:{title:'LEGEND DRIVE',desc:'Neon otoyol arcade yarışı',speed:'HIZ',dist:'MESAFE',score:'SKOR',nitro:'NITRO',restart:'Yenile R',camera:'Kamera C'}};
let lang='en';
function mat(c,em=0){return new THREE.MeshStandardMaterial({color:c,emissive:em,emissiveIntensity:em?1.5:0,metalness:.45,roughness:.28})}function cube(w,h,d,c,y=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.y=y;return m}
function clearWorld(){while(scene.children.length>2)scene.remove(scene.children[2]);buildWorld()}
function buildWorld(){const e=state.env;let sky=0x080a13,roadC=0x252832,side=0x10151d,groundC=0x10141b; if(e==='day'){sky=0x7ca7c8;roadC=0x35383d;side=0x56724c;groundC=0x496b45}if(e==='sunset'){sky=0x2b1831;roadC=0x292a32;side=0x46302b;groundC=0x302326}if(e==='desert'){sky=0xd69a64;roadC=0x363238;side=0xb77b49;groundC=0x9b6741}scene.background=new THREE.Color(sky);scene.fog.color.setHex(sky);const ground=new THREE.Mesh(new THREE.PlaneGeometry(600,900),mat(groundC));ground.rotation.x=-Math.PI/2;ground.position.z=-180;scene.add(ground);const road=new THREE.Mesh(new THREE.PlaneGeometry(17,900),mat(roadC));road.rotation.x=-Math.PI/2;road.position.y=.02;road.position.z=-180;scene.add(road);for(const x of[-9.2,9.2]){const s=cube(1.8,.08,900,side);s.position.set(x,.06,-180);scene.add(s)}for(const x of[-2.83,2.83])for(let z=-620;z<300;z+=11){const l=cube(.13,.035,5.5,0xf2f0df,.08);l.position.x=x;l.position.z=z;scene.add(l)}if(e==='neon'){for(let i=0;i<34;i++){const h=4+Math.random()*15,w=2+Math.random()*5,x=(Math.random()<.5?-1:1)*(11+Math.random()*18),z=-i*25-Math.random()*18;const b=cube(w,h,w,0x131a2a,h/2);b.position.x=x;b.position.z=z;scene.add(b);const neon=cube(w*.9,.12,.15,0x1ec8ff,Math.max(0,0x1ec8ff));neon.material.emissive=new THREE.Color(0x1ec8ff);neon.material.emissiveIntensity=3;neon.position.set(x,h*.65,z-w/2);scene.add(neon)}}else{for(let i=0;i<30;i++){const h=3+Math.random()*9,w=2+Math.random()*4,x=(Math.random()<.5?-1:1)*(12+Math.random()*20),z=-i*30-Math.random()*15;const b=cube(w,h,w,0x34404b,h/2);b.position.set(x,0,z);scene.add(b)}}}
buildWorld();
const carDefs={gtr:{name:'GTR-X',color:0x21b6ff,acc:34,max:102},supra:{name:'SUPRA-R',color:0xffb321,acc:32,max:106},gt:{name:'GT-V12',color:0xd9e3ee,acc:30,max:112},rally:{name:'RALLY-X',color:0xff3e61,acc:36,max:98}};
function makePlayer(def){const g=new THREE.Group();const body=cube(2.05,.52,4.45,def.color,.62);g.add(body);const nose=cube(1.86,.2,1.15,def.color,.91);nose.position.z=-1.6;g.add(nose);const roof=cube(1.48,.62,1.72,0x111a2b,1.02);roof.position.z=.25;g.add(roof);const glass=cube(1.3,.16,1.1,0x4bc9ff,.98);glass.position.z=-.05;g.add(glass);for(const x of[-.94,.94])for(const z of[-1.45,1.45]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.36,.36,.25,20),mat(0x07080b));w.rotation.z=Math.PI/2;w.position.set(x,.4,z);g.add(w)}const glow=cube(1.7,.06,.12,0x19d8ff,.5);glow.position.set(0,.54,2.18);g.add(glow);return g}
let player=makePlayer(carDefs[state.car]);player.position.set(0,0,8);scene.add(player);
function makeTraffic(color){const g=new THREE.Group();g.add(cube(1.9,.5,4.2,color,.6));const cab=cube(1.4,.55,1.7,0x182333,1.0);cab.position.z=.2;g.add(cab);for(const x of[-.88,.88])for(const z of[-1.3,1.3]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.33,.33,.22,18),mat(0x07080b));w.rotation.z=Math.PI/2;w.position.set(x,.4,z);g.add(w)}return g}
const traffic=[],trafficColors=[0xffffff,0xd94355,0xffc833,0x5c70e8,0x2fb36e,0x8f96a0,0x14161b];for(let i=0;i<18;i++){const t=makeTraffic(trafficColors[i%trafficColors.length]);t.position.set((Math.floor(Math.random()*5)-2)*2.83,0,-35-i*28-Math.random()*25);t.userData.speed=25+Math.random()*38;t.userData.lane=Math.round(t.position.x/2.83);scene.add(t);traffic.push(t)}
function reset(){state.speed=0;state.nitro=100;state.distance=0;state.score=0;state.crashed=false;player.position.set(0,0,8);document.getElementById('crash').classList.add('hidden');traffic.forEach((t,i)=>{t.position.z=-35-i*30-Math.random()*20;t.position.x=(Math.floor(Math.random()*5)-2)*2.83})}
function localize(){const x=I18N[lang];document.getElementById('title').textContent=x.title;document.getElementById('desc').textContent=x.desc;document.getElementById('camera').textContent=x.camera;document.getElementById('restart').textContent=x.restart;document.documentElement.dir=lang==='fa'||lang==='ar'?'rtl':'ltr'}
document.getElementById('lang').onchange=e=>{lang=e.target.value;localize()};document.getElementById('environment').onchange=e=>{state.env=e.target.value;clearWorld()};document.getElementById('carSelect').onchange=e=>{state.car=e.target.value;scene.remove(player);player=makePlayer(carDefs[state.car]);player.position.set(0,0,8);scene.add(player);document.getElementById('carName').textContent=carDefs[state.car].name};document.getElementById('camera').onclick=()=>state.cam=(state.cam+1)%4;document.getElementById('traffic').onclick=()=>{state.twoWay=!state.twoWay;document.getElementById('traffic').textContent=state.twoWay?'One Way':'Two Way'};document.getElementById('restart').onclick=reset;
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyC')state.cam=(state.cam+1)%4;if(e.code==='KeyR')reset()});addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('.touch').forEach(b=>{const k=b.dataset.key;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function loop(now){const dt=Math.min(.033,(now-state.last)/1000);state.last=now;if(!state.crashed){const d=carDefs[state.car],gas=keys.KeyW||keys.ArrowUp,brake=keys.KeyS||keys.ArrowDown;if(gas)state.speed+=d.acc*dt;else state.speed-=9*dt;if(brake)state.speed-=48*dt;if((keys.ShiftLeft||keys.ShiftRight)&&state.nitro>0){state.speed+=62*dt;state.nitro-=38*dt}else state.nitro=Math.min(100,state.nitro+10*dt);state.speed=Math.max(0,Math.min(d.max,state.speed));let steer=((keys.KeyD||keys.ArrowRight)?-1:0)+((keys.KeyA||keys.ArrowLeft)?1:0);player.position.x+=steer*(2.0+state.speed*.035)*dt;player.position.x=Math.max(-7,Math.min(7,player.position.x));player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-steer*.08,.18);state.distance+=state.speed*dt*.34;state.score+=state.speed*dt*.95;for(const t of traffic){const rel=state.speed-t.userData.speed;t.position.z+=rel*dt;if(state.twoWay&&Math.random()<.001)t.userData.speed=-Math.abs(t.userData.speed);if(t.position.z>player.position.z+25){t.position.z=player.position.z-420-Math.random()*220;t.position.x=(Math.floor(Math.random()*5)-2)*2.83;t.userData.speed=25+Math.random()*40}if(Math.abs(t.position.x-player.position.x)<1.65&&Math.abs(t.position.z-player.position.z)<2.5){state.crashed=true;document.getElementById('crash').classList.remove('hidden')}}}
const camTargets=[new THREE.Vector3(player.position.x,4.1,player.position.z+9),new THREE.Vector3(player.position.x,2.0,player.position.z+5),new THREE.Vector3(player.position.x,7.8,player.position.z+14),new THREE.Vector3(player.position.x,1.4,player.position.z-2.5)];camera.position.lerp(camTargets[state.cam],.12);camera.lookAt(player.position.x,.8,player.position.z-15);document.getElementById('speed').textContent=Math.round(state.speed*3.4);document.getElementById('distance').textContent=Math.floor(state.distance);document.getElementById('score').textContent=Math.floor(state.score);document.getElementById('nitro').textContent=Math.floor(state.nitro);renderer.render(scene,camera);requestAnimationFrame(loop)}localize();requestAnimationFrame(loop);