const MODES=[['infinite','∞ Infinite','Endless highway.'],['time','⏱ Against Time','Reach checkpoints before time runs out.'],['two','↕ Two Way','Traffic comes from both directions.'],['free','▥ Free Ride','Cruise without score pressure.'],['career','🏁 Career','Progress through a sequence of races.'],['rush','🔥 Traffic Rush','Heavy traffic and aggressive speed.'],['checkpoint','🚩 Checkpoint','Pass checkpoints to extend your run.'],['drift','💨 Drift Run','Earn points from controlled slides.'],['night','🌙 Night Drive','Neon night highway challenge.'],['sunset','🌇 Sunset Drive','Golden-hour highway run.']];
const panelData={shop:['SHOP',['Starter Pack','Nitro Refill','Street Wheels','Neon Paint','Carbon Wing']],custom:['CUSTOMIZE',['Body Color','Wheels','Spoiler','Neon','Window Tint']],leader:['LEADERBOARD',['1  LEGEND_01  —  98,420','2  SPEEDKING  —  91,775','3  GTR_FAN  —  87,240','4  NIGHTRUN  —  81,640','5  YOU  —  0']],settings:['SETTINGS',['Graphics: High','Traffic: High','Camera: Chase','Units: KM/H','Language: Auto']]];
function modal(title,html){const m=document.getElementById('modal'),t=document.getElementById('modalTitle'),b=document.getElementById('modalBody');if(!m||!t||!b)return;t.textContent=title;b.innerHTML=html;m.classList.remove('hidden')}
function closeModal(){document.getElementById('modal')?.classList.add('hidden')}
function chooseMode(id){localStorage.setItem('legend_mode',id);closeModal();const race=document.querySelector('[data-open="modes"]');if(race)race.click()}
function showModes(){modal('RACE MODES','<div class="grid">'+MODES.map(m=>`<button class="choice modeChoice" data-mode="${m[0]}"><b>${m[1]}</b><small>${m[2]}</small></button>`).join('')+'</div>');document.querySelectorAll('.modeChoice').forEach(x=>x.onclick=()=>chooseMode(x.dataset.mode))}
function showPanel(type){const p=panelData[type];if(!p)return;modal(p[0],'<div class="grid">'+p[1].map((x,i)=>`<div class="choice"><b>${x}</b><small>${i===0?'Available now':'Locked / coming soon'}</small></div>`).join('')+'</div>')}
function showGarage(){const cars=[['SUPRA-X','330 KM/H'],['GTR-X','350 KM/H'],['GT-V12','365 KM/H'],['RALLY-X','315 KM/H']];modal('GARAGE','<div class="grid">'+cars.map((c,i)=>`<button class="choice ${i===1?'selected':''}" data-car="${c[0]}"><div class="swatch" style="background:linear-gradient(135deg,${['#ff6b17','#e9eef5','#246bff','#ff285c'][i]},#101522)"></div><b>${c[0]}</b><small>${c[1]} · ${i===1?'Selected':'Select'}</small></button>`).join('')+'</div>');document.querySelectorAll('[data-car]').forEach(x=>x.onclick=()=>{document.getElementById('heroCar').textContent=x.dataset.car;closeModal()})}
function wire(){document.getElementById('close')?.addEventListener('click',closeModal);document.querySelectorAll('[data-open]').forEach(btn=>{btn.addEventListener('click',e=>{const type=btn.dataset.open;if(type==='modes'){e.preventDefault();showModes()}else if(type==='garage'){e.preventDefault();showGarage()}else if(panelData[type]){e.preventDefault();showPanel(type)}})});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lang]').forEach(x=>x.classList.remove('on'));b.classList.add('on');localStorage.setItem('legend_lang',b.dataset.lang)});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();