/* Legend Drive V5 — stable menu layer. Does not replace the V4 engine. */
(()=>{
'use strict';
const MODES=[['infinite','∞ Infinite','Endless highway.'],['time','⏱ Against Time','Beat the clock.'],['two','↕ Two Way','Traffic both directions.'],['free','▥ Free Ride','No score pressure.'],['career','🏁 Career','Race progression.'],['rush','🔥 Traffic Rush','Heavy traffic.'],['checkpoint','🚩 Checkpoint','Pass checkpoints.'],['drift','💨 Drift Run','Drift scoring.'],['night','🌙 Night Drive','Night challenge.'],['sunset','🌇 Sunset Drive','Golden hour.'],['desert','🏜️ Desert Run','Desert highway.'],['city','🏙️ City Rush','Urban traffic.']];
const GARAGE=[['supra','SUPRA-X','330 KM/H','WIDEBODY','#ff6b17'],['gtr','GTR-X','350 KM/H','AWD STREET','#e9eef5'],['gt','GT-V12','365 KM/H','GRAND TOURER','#246bff'],['rally','RALLY-X','315 KM/H','RALLY','#ff285c'],['rx7','RX-7R','325 KM/H','ROTARY','#ffd22e'],['silvia','SILVIA-S','310 KM/H','DRIFT','#7c55ff'],['evo','EVO-XR','320 KM/H','RALLY STREET','#35b9a8'],['muscle','V8-BEAST','305 KM/H','MUSCLE','#9c2028'],['hyper','HYPER-Z','390 KM/H','HYPERCAR','#0ee7ff'],['retro','RETRO-GT','285 KM/H','CLASSIC','#d6b07a']];
const SHOP=[['Nitro Refill','Refill nitro between runs',250,'nitro'],['Race Tires','Better grip',900,'grip'],['Performance ECU','Higher top speed',1800,'ecu'],['Turbo Kit','Faster acceleration',2200,'turbo'],['Carbon Wing','Track aero',1400,'wing'],['Neon Kit','Underbody glow',1600,'neon'],['Street Wheels','New wheel set',1200,'wheels'],['Premium Paint','Custom paint slot',1100,'paint']];
const COLORS=[['Arctic White','#e9eef5'],['Inferno Orange','#ff5b16'],['Electric Blue','#246bff'],['Neon Cyan','#0ee7ff'],['Lime Pulse','#35d27b'],['Royal Purple','#8a5cff'],['Gold Rush','#ffd22e'],['Crimson','#d52f48']];
const KEY='legend_drive_menu_v5';
let data=JSON.parse(localStorage.getItem(KEY)||'{}');
data.cash=Number.isFinite(data.cash)?data.cash:25000;data.owned=Array.isArray(data.owned)?data.owned:[];data.custom=data.custom||{};data.traffic=data.traffic||{density:'high',speed:'mixed',style:'normal'};
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const $=id=>document.getElementById(id);
function modal(title,html){const m=$('modal');if(!m)return;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;m.classList.remove('hidden')}
function closeModal(){$('modal')?.classList.add('hidden')}
function showModes(){modal('RACE MODES','<div class="grid">'+MODES.map(m=>`<button type="button" class="choice modeChoice" data-mode="${m[0]}"><b>${m[1]}</b><small>${m[2]}</small></button>`).join('')+'</div>');document.querySelectorAll('.modeChoice').forEach(b=>b.onclick=()=>chooseMode(b.dataset.mode))}
function chooseMode(id){localStorage.setItem('legend_mode',id);localStorage.setItem('legend_mode_label',MODES.find(x=>x[0]===id)?.[1]||id);closeModal();window.legendStarting=true;window.dispatchEvent(new CustomEvent('legend:mode',{detail:{id}}));const race=document.querySelector('[data-open="modes"]');if(race){race.dataset.selectedMode=id;setTimeout(()=>race.click(),0)}setTimeout(()=>{window.legendStarting=false},160)}
function showGarage(){const selected=localStorage.getItem('legend_car')||'gtr';modal('GARAGE — YOUR FLEET','<div class="grid">'+GARAGE.map(c=>`<button type="button" class="choice ${c[0]===selected?'selected':''}" data-car="${c[0]}"><div class="swatch" style="height:90px;background:linear-gradient(135deg,${c[4]},#101522)"></div><b>${c[1]}</b><small>${c[2]} · ${c[3]}</small></button>`).join('')+'</div>');document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>selectCar(b.dataset.car))}
function selectCar(id){const c=GARAGE.find(x=>x[0]===id);if(!c)return;localStorage.setItem('legend_car',id);if($('heroCar'))$('heroCar').textContent=c[1];if($('heroStats'))$('heroStats').textContent=c[2]+' · '+c[3]+' · STREET LEGEND';window.dispatchEvent(new CustomEvent('legend:car',{detail:{id}}));showGarage()}
function showShop(){modal('SHOP — PERFORMANCE & STYLE',`<div style="margin-bottom:14px;font-size:18px">💵 <b>${data.cash.toLocaleString()}</b></div><div class="grid">${SHOP.map(x=>`<button type="button" class="choice shopItem" data-item="${x[3]}"><b>${x[0]}</b><small>${x[1]}</small><span style="display:block;margin-top:8px;color:${data.owned.includes(x[3])?'#45e28a':'#ffd24a'}">${data.owned.includes(x[3])?'OWNED ✓':'$'+x[2].toLocaleString()}</span></button>`).join('')}</div>`);document.querySelectorAll('.shopItem').forEach(b=>b.onclick=()=>{const x=SHOP.find(y=>y[3]===b.dataset.item);if(!x||data.owned.includes(x[3]))return;if(data.cash<x[2]){b.animate([{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:180});return}data.cash-=x[2];data.owned.push(x[3]);save();showShop();window.dispatchEvent(new CustomEvent('legend:shop',{detail:{item:x[3],owned:data.owned}}))})}
function showCustom(){const id=localStorage.getItem('legend_car')||'gtr';const c=data.custom[id]||{};modal('CUSTOMIZE — '+id.toUpperCase(),`<div class="grid"><div class="choice"><b>BODY PAINT</b><div class="lang" style="margin-top:10px">${COLORS.map(x=>`<button type="button" class="paint ${c.paint===x[1]?'on':''}" data-color="${x[1]}" style="border:2px solid ${x[1]};width:34px;height:34px;border-radius:50%;padding:0"></button>`).join('')}</div></div><div class="choice"><b>NEON</b><div class="lang" style="margin-top:10px"><button type="button" class="neon ${c.neon?'on':''}" data-v="1">ON</button><button type="button" class="neon ${!c.neon?'on':''}" data-v="0">OFF</button></div><small>Window tint</small><div class="lang"><button type="button" class="tint ${c.tint===20?'on':''}" data-v="20">LIGHT</button><button type="button" class="tint ${c.tint===60?'on':''}" data-v="60">DARK</button></div></div></div>`);document.querySelectorAll('.paint').forEach(b=>b.onclick=()=>{data.custom[id]=data.custom[id]||{};data.custom[id].paint=b.dataset.color;save();emitCustom(id);showCustom()});document.querySelectorAll('.neon').forEach(b=>b.onclick=()=>{data.custom[id]=data.custom[id]||{};data.custom[id].neon=b.dataset.v==='1';save();emitCustom(id);showCustom()});document.querySelectorAll('.tint').forEach(b=>b.onclick=()=>{data.custom[id]=data.custom[id]||{};data.custom[id].tint=Number(b.dataset.v);save();emitCustom(id);showCustom()})}
function emitCustom(id){window.dispatchEvent(new CustomEvent('legend:custom',{detail:{car:id,custom:data.custom[id]}}))}
function showTraffic(){const t=data.traffic;modal('TRAFFIC CONTROL',`<div class="choice"><b>TRAFFIC DENSITY</b><div class="lang" style="margin-top:10px">${['low','medium','high','insane'].map(x=>`<button type="button" class="td ${t.density===x?'on':''}" data-v="${x}">${x.toUpperCase()}</button>`).join('')}</div><b style="display:block;margin-top:18px">TRAFFIC SPEED</b><div class="lang">${['slow','mixed','fast'].map(x=>`<button type="button" class="ts ${t.speed===x?'on':''}" data-v="${x}">${x.toUpperCase()}</button>`).join('')}</div><b style="display:block;margin-top:18px">DRIVING STYLE</b><div class="lang"><button type="button" class="ta ${t.style==='normal'?'on':''}" data-v="normal">NORMAL</button><button type="button" class="ta ${t.style==='aggressive'?'on':''}" data-v="aggressive">AGGRESSIVE</button></div><small style="display:block;margin-top:14px">Settings are saved and sent to the game engine.</small></div>`);document.querySelectorAll('.td').forEach(b=>b.onclick=()=>setTraffic('density',b.dataset.v));document.querySelectorAll('.ts').forEach(b=>b.onclick=()=>setTraffic('speed',b.dataset.v));document.querySelectorAll('.ta').forEach(b=>b.onclick=()=>setTraffic('style',b.dataset.v))}
function setTraffic(key,value){data.traffic[key]=value;save();window.dispatchEvent(new CustomEvent('legend:traffic',{detail:{...data.traffic}}));showTraffic()}
function showPanel(type){if(type==='shop')return showShop();if(type==='custom')return showCustom();if(type==='traffic')return showTraffic();const panels={leader:['LEADERBOARD',['1  LEGEND_01 — 98,420','2  SPEEDKING — 91,775','3  GTR_FAN — 87,240','4  NIGHTRUN — 81,640','5  YOU — 0']],settings:['SETTINGS',['Graphics: High','Camera: Chase','Units: KM/H','Effects: High','Touch Controls: On']]};const p=panels[type];if(p)modal(p[0],'<div class="grid">'+p[1].map(x=>`<div class="choice"><b>${x}</b></div>`).join('')+'</div>')}
function wire(){const close=$('close');if(close)close.onclick=closeModal;document.querySelectorAll('[data-open]').forEach(btn=>{btn.addEventListener('click',e=>{if(window.legendStarting)return;e.preventDefault();e.stopImmediatePropagation();const type=btn.dataset.open;if(type==='modes')showModes();else if(type==='garage')showGarage();else showPanel(type)},true)});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lang]').forEach(x=>x.classList.remove('on'));b.classList.add('on');localStorage.setItem('legend_lang',b.dataset.lang)});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();