const MODES=[['infinite','∞ Infinite','Endless highway.'],['time','⏱ Against Time','Reach checkpoints before time runs out.'],['two','↕ Two Way','Traffic comes from both directions.'],['free','▥ Free Ride','Cruise without score pressure.'],['career','🏁 Career','Progress through a sequence of races.'],['rush','🔥 Traffic Rush','Heavy traffic and aggressive speed.'],['checkpoint','🚩 Checkpoint','Pass checkpoints to extend your run.'],['drift','💨 Drift Run','Earn points from controlled slides.'],['night','🌙 Night Drive','Neon night highway challenge.'],['sunset','🌇 Sunset Drive','Golden-hour highway run.'],['desert','🏜️ Desert Run','High-speed desert highway.'],['city','🏙️ City Rush','Dense urban traffic and neon lights.']];
const GARAGE=[['supra','SUPRA-X','330 KM/H','WIDEBODY'],['gtr','GTR-X','350 KM/H','AWD STREET'],['gt','GT-V12','365 KM/H','GRAND TOURER'],['rally','RALLY-X','315 KM/H','RALLY'],['rx7','RX-7R','325 KM/H','ROTARY'],['silvia','SILVIA-S','310 KM/H','DRIFT'],['evo','EVO-XR','320 KM/H','RALLY STREET'],['muscle','V8-BEAST','305 KM/H','MUSCLE'],['hyper','HYPER-Z','390 KM/H','HYPERCAR'],['retro','RETRO-GT','285 KM/H','CLASSIC']];
const panelData={shop:['SHOP',['Starter Pack','Nitro Refill','Street Wheels','Neon Paint','Carbon Wing','Performance ECU','Race Tires','Engine Upgrade']],custom:['CUSTOMIZE',['Body Color','Wheels','Spoiler','Neon','Window Tint','Bumper','Hood','Exhaust']],leader:['LEADERBOARD',['1  LEGEND_01  —  98,420','2  SPEEDKING  —  91,775','3  GTR_FAN  —  87,240','4  NIGHTRUN  —  81,640','5  YOU  —  0']],settings:['SETTINGS',['Graphics: High','Traffic: High','Camera: Chase','Units: KM/H','Language: Auto','Effects: High','Shadows: High','Touch Controls: On']]};
function modal(title,html){const m=document.getElementById('modal'),t=document.getElementById('modalTitle'),b=document.getElementById('modalBody');if(!m||!t||!b)return;t.textContent=title;b.innerHTML=html;m.classList.remove('hidden')}
function closeModal(){document.getElementById('modal')?.classList.add('hidden')}
function chooseMode(id){localStorage.setItem('legend_mode',id);closeModal();window.legendStarting=true;window.dispatchEvent(new CustomEvent('legend:mode',{detail:{id}}));const race=document.querySelector('[data-open="modes"]');if(race)race.dataset.selectedMode=id;setTimeout(()=>window.legendStarting=false,50)}
function showModes(){modal('RACE MODES','<div class="grid">'+MODES.map(m=>`<button class="choice modeChoice" data-mode="${m[0]}"><b>${m[1]}</b><small>${m[2]}</small></button>`).join('')+'</div>');document.querySelectorAll('.modeChoice').forEach(x=>x.onclick=()=>chooseMode(x.dataset.mode))}
function showPanel(type){const p=panelData[type];if(!p)return;modal(p[0],'<div class="grid">'+p[1].map((x,i)=>`<div class="choice"><b>${x}</b><small>${i===0?'Available now':'Ready for upgrade'}</small></div>`).join('')+'</div>')}
function selectCar(id){const c=GARAGE.find(x=>x[0]===id);if(!c)return;localStorage.setItem('legend_car',id);document.getElementById('heroCar').textContent=c[1];document.getElementById('heroStats').textContent=c[2]+' · '+c[3]+' · STREET LEGEND';window.dispatchEvent(new CustomEvent('legend:car',{detail:{id}}));document.querySelectorAll('[data-car]').forEach(x=>x.classList.toggle('selected',x.dataset.car===id));}
function showGarage(){const selected=localStorage.getItem('legend_car')||'gtr';modal('GARAGE','<div class="grid">'+GARAGE.map(c=>`<button class="choice ${c[0]===selected?'selected':''}" data-car="${c[0]}"><div class="swatch" style="background:linear-gradient(135deg,${({'supra':'#ff6b17','gtr':'#e9eef5','gt':'#246bff','rally':'#ff285c','rx7':'#ffd22e','silvia':'#7c55ff','evo':'#35b9a8','muscle':'#9c2028','hyper':'#0ee7ff','retro':'#d6b07a'})[c[0]]},#101522)"></div><b>${c[1]}</b><small>${c[2]} · ${c[3]}</small></button>`).join('')+'</div>');document.querySelectorAll('[data-car]').forEach(x=>x.onclick=()=>selectCar(x.dataset.car))}
function wire(){document.getElementById('close')?.addEventListener('click',closeModal);document.querySelectorAll('[data-open]').forEach(btn=>{btn.addEventListener('click',e=>{const type=btn.dataset.open;e.preventDefault();e.stopImmediatePropagation();if(type==='modes')showModes();else if(type==='garage')showGarage();else if(panelData[type])showPanel(type)},true)});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lang]').forEach(x=>x.classList.remove('on'));b.classList.add('on');localStorage.setItem('legend_lang',b.dataset.lang)});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();