/* LEGEND DRIVE V5 — META/UX UPGRADE
   Works with the existing V4 3D engine and adds progression, missions,
   daily challenge, weather FX, combo scoring, achievements, telemetry and polish.
*/
(()=>{
'use strict';
const SAVE='legend_drive_v5_meta';
const S=JSON.parse(localStorage.getItem(SAVE)||'{}');
const state={coins:S.coins||0,xp:S.xp||0,level:S.level||1,combo:S.combo||1,best:S.best||0,near:S.near||0,weather:S.weather||'auto',daily:S.daily||0,ach:S.ach||[],lastScore:0,lastDist:0,lastSpeed:0,running:false,startedAt:0};
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem(SAVE,JSON.stringify(state));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function css(){const s=document.createElement('style');s.textContent=`#v5panel{position:fixed;z-index:12;top:74px;left:14px;width:min(330px,calc(100vw - 28px));padding:14px;border:1px solid #ffffff20;border-radius:16px;background:linear-gradient(135deg,#080b16eF,#11182beF);backdrop-filter:blur(12px);box-shadow:0 18px 60px #0008;display:none;font:700 13px system-ui;color:#fff}#v5panel.show{display:block}.v5row{display:flex;justify-content:space-between;gap:8px;margin:6px 0}.v5bar{height:7px;border-radius:8px;background:#ffffff14;overflow:hidden}.v5bar i{display:block;height:100%;width:0;background:linear-gradient(90deg,#ff4216,#ffe14a,#1ce6ff)}.v5btn{padding:8px 10px;border-radius:9px;background:#ffffff12;color:#fff;border:1px solid #ffffff18;cursor:pointer;font-weight:800}.v5chips{display:flex;gap:6px;flex-wrap:wrap}.v5chip{padding:6px 8px;border-radius:8px;background:#0b1020;border:1px solid #ffffff14}.ld-toast{position:fixed;z-index:50;left:50%;top:18%;transform:translateX(-50%);padding:12px 18px;border-radius:14px;background:#070a12ee;border:1px solid #ffffff2a;box-shadow:0 14px 60px #0008;display:grid;gap:3px;text-align:center;animation:v5in .2s ease-out;font:700 14px system-ui;color:#fff}.ld-toast b{font-size:20px;color:#ff6b1b}.ld-toast span{opacity:.8}@keyframes v5in{from{opacity:0;transform:translate(-50%,-10px)}to{opacity:1;transform:translate(-50%,0)}}#v5flash{position:fixed;inset:0;z-index:7;pointer-events:none;opacity:0;transition:opacity .15s;background:radial-gradient(circle at center,#1adfff22,transparent 55%)}#v5flash.on{opacity:1}#v5weather{position:fixed;inset:0;z-index:6;pointer-events:none;opacity:0;transition:opacity .35s}#v5weather.rain{opacity:.32;background:repeating-linear-gradient(105deg,transparent 0 9px,#9edaff22 10px 11px,transparent 12px 22px);animation:rain .35s linear infinite}@keyframes rain{to{background-position:60px 120px}}#v5speedline{position:fixed;inset:0;z-index:6;pointer-events:none;opacity:0;background:radial-gradient(ellipse at center,transparent 42%,#fff1 43%,transparent 44%),radial-gradient(ellipse at center,transparent 55%,#fff1 56%,transparent 57%);mix-blend-mode:screen}#v5speedline.on{opacity:.65;animation:speedpulse .22s linear infinite}@keyframes speedpulse{50%{transform:scale(1.035)}}#v5toggle{position:fixed;z-index:13;top:14px;right:14px;display:none;padding:9px 12px;border-radius:10px;background:#070a13dd;border:1px solid #ffffff22;color:#fff;font-weight:900;cursor:pointer}.v5run #v5toggle{display:block}#crashOverlay{backdrop-filter:blur(8px)}#restartRun{border:0;border-radius:12px;padding:12px 24px;background:linear-gradient(90deg,#ff4216,#ff7a1a);color:#fff;font-weight:1000;cursor:pointer}`;document.head.appendChild(s)}
function makeUI(){document.body.insertAdjacentHTML('beforeend',`<div id="v5weather"></div><div id="v5flash"></div><div id="v5speedline"></div><button id="v5toggle">☰ V5</button><div id="v5panel"><div style="font-size:20px;font-style:italic">LEGEND DRIVE <span style="color:#ff5a1a">V5</span></div><div class="v5row"><span>LEVEL <b id="v5level">1</b></span><span>COINS <b id="v5coins">0</b></span><span>COMBO <b id="v5combo">x1</b></span></div><div class="v5row"><span>XP</span><span id="v5xp">0 / 1000</span></div><div class="v5bar"><i id="v5xpbar"></i></div><hr style="border:0;border-top:1px solid #ffffff12;margin:12px 0"><div style="opacity:.65">ACTIVE MISSION</div><div id="v5mission" style="font-size:16px;margin:4px 0 10px">Start a race</div><div class="v5chips" id="v5ach"></div><div style="display:flex;gap:6px;margin-top:12px"><button class="v5btn" id="v5weatherBtn">🌦 Weather</button><button class="v5btn" id="v5saveBtn">💾 Save</button><button class="v5btn" id="v5resetBtn">↻ Meta Reset</button></div><div style="opacity:.45;margin-top:10px">V = panel · C = camera · R = restart · T = weather</div></div>`);$('v5toggle').onclick=()=>$('v5panel').classList.toggle('show');$('v5weatherBtn').onclick=cycleWeather;$('v5saveBtn').onclick=()=>{save();toast('SAVED','Progress stored locally')};$('v5resetBtn').onclick=()=>{if(confirm('Reset V5 progression?')){localStorage.removeItem(SAVE);location.reload()}}}
const missions=[['SPEED DEMON','Reach 300 KM/H',300,'speed'],['ROAD WARRIOR','Drive 5 km',5000,'distance'],['SCORE ATTACK','Score 25,000',25000,'score'],['COMBO MASTER','Reach x5 combo',5,'combo']];
let missionIndex=S.missionIndex||0,missionValue=S.missionValue||0;
function mission(){return missions[missionIndex%missions.length]}
function toast(a,b){const d=document.createElement('div');d.className='ld-toast';d.innerHTML='<b>'+a+'</b><span>'+b+'</span>';document.body.appendChild(d);setTimeout(()=>d.remove(),1700)}
function award(x){state.xp+=x;let need=1000+state.level*500;while(state.xp>=need){state.xp-=need;state.level++;state.coins+=1000;toast('LEVEL UP','LEVEL '+state.level);need=1000+state.level*500}state.coins+=Math.floor(x/20);save()}
function unlock(a){if(state.ach.includes(a))return;state.ach.push(a);award(150);toast('ACHIEVEMENT',a)}
function cycleWeather(){const w=['auto','clear','rain','night','sunset'];state.weather=w[(w.indexOf(state.weather)+1)%w.length];applyWeather();save();toast('WEATHER',state.weather.toUpperCase())}
function applyWeather(){const el=$('v5weather');if(!el)return;el.className=state.weather==='rain'?'rain':'';if(state.weather==='night'){document.documentElement.style.filter='brightness(.78) saturate(1.18)'}else if(state.weather==='sunset'){document.documentElement.style.filter='sepia(.18) saturate(1.18)'}else{document.documentElement.style.filter='none'}}
function runState(){const hud=$('hud');const visible=hud&&getComputedStyle(hud).display!=='none';if(visible&&!state.running){state.running=true;state.startedAt=performance.now();toast('V5 ACTIVE','Progress + missions enabled');document.body.classList.add('v5run')}}
function read(id){const x=$(id)?.textContent||'0';return parseFloat(x.replace(/[^0-9.\-]/g,''))||0}
function tick(){runState();if(state.running){const speed=read('speed'),score=read('score'),dist=read('distance'),nitro=read('nitro');state.best=Math.max(state.best,score);if(speed>295)unlock('300 CLUB');if(dist>=1000)unlock('1 KM');if(score>=10000)unlock('10K');if(speed>320&&nitro<70)state.combo=clamp(state.combo+.015,1,9);else state.combo=Math.max(1,state.combo-.006);if(speed>250)$('v5speedline')?.classList.add('on');else $('v5speedline')?.classList.remove('on');if(speed>295&&Math.random()<.025){state.coins++;$('v5flash')?.classList.add('on');setTimeout(()=>$('v5flash')?.classList.remove('on'),90)}const m=mission();let value=m[3]==='speed'?speed:m[3]==='distance'?dist:m[3]==='score'?score:state.combo;missionValue=Math.max(missionValue,value);if(missionValue>=m[2]){toast('MISSION COMPLETE',m[0]);award(500);missionIndex++;missionValue=0;save()}sync(speed,score,dist,nitro)}}else $('v5speedline')?.classList.remove('on');requestAnimationFrame(tick)}
function sync(speed,score,dist,nitro){const need=1000+state.level*500;const p=clamp(state.xp/need*100,0,100);$('v5level').textContent=state.level;$('v5coins').textContent=state.coins;$('v5combo').textContent='x'+state.combo.toFixed(1);$('v5xp').textContent=Math.floor(state.xp)+' / '+need;$('v5xpbar').style.width=p+'%';const m=mission();$('v5mission').textContent=m[0]+' — '+Math.floor(missionValue)+' / '+m[2];const ach=$('v5ach');ach.innerHTML=state.ach.slice(-6).map(a=>`<span class="v5chip">🏆 ${a}</span>`).join('')||'<span class="v5chip">No achievements yet</span>';state.lastScore=score;state.lastDist=dist;state.lastSpeed=speed;}
css();makeUI();applyWeather();
addEventListener('keydown',e=>{if(e.code==='KeyV')$('v5panel').classList.toggle('show');if(e.code==='KeyT')cycleWeather();if(e.code==='KeyP')$('v5panel').classList.toggle('show')});
setInterval(save,8000);requestAnimationFrame(tick);
})();
